### ISSUE TITLE
Option to choose CNs instead of having them auto-form

### ISSUE THREAD

**Issue by Dragonkn1ght** [RohanTLK/Make-Europa-Great-Again#15]

**Comment by ComradeL1berty** [comment]
Apparently you just wait for them to rebel and re annex?

**Comment by SpectreOfRohan** [comment]
Nah it just turns into a new CN as soon as you core 5 provinces. This probably isn't even a balance issue tbh I just found it annoying that I never got a choice when playing as a colonial
